public class A{//sdfdfghhg

// Account a1 = new Account(); giri
Account a111 = new Account();
Contact c = new Contact();
Contact c111 = new Contact();//fdfd
Contact EEE = new Contact();
//ssdssd
//dsdsds
//dsdsds
Contact FFF111 = new Contact();//sdfsdf
Contact FFF112 = new Contact();
Contact FFF11modi = new Contact();
Account a1 = new Account();
//checkinshamjfdsfdsfdsfdsjll
// this.weekDayPattern,
// this.weekDayPattern
//sdfsdfsdf
}