public Class A03
//HelloAR
{
public Account createAccount(String name) //method to create account
{
Account sai55= new Account();
sai55.Name = name;
return sai55; 
//Modify new trialcommnet 98321
// sldkjfsldkjflsdkjflskjdflkj
// sldkfjsldkf te d09sa321 test calk03921
// sdlfkjds te ca-09321 apex clasd java 98321
//sdfsdfdsf far983921
//apex clasdsad pomegranate
//source class 03 test check001 source after build
//test source class 0909321
//test clasd 909321
//jsaiupaiousp9ausd9pa
//dsaidaipdjspa
//test clksa oiuw9898921
//lksaoi98921
}        
}