public Class A079
//HelloAR
{
public Account createAccount(String name) //method to create account
{
Account sai55= new Account();
sai55.Name = name;
return sai55; 
//dsa tes dsa 8321
// hgdsa  test 9321321 tes 09321312 clas321 tes clas 09321
// test 666721 test 556521 clas 83211212
// tes 86767321 west 77711clas 08321 test clasd90321321
//dsa test dsa jiuiuwq test tets clas fdsfdsffddg
}        
}