public Class A1101
//HelloAR
{
public Account createAccount(String name) //method to create account
{
Account sai55= new Account();
sai55.Name = name;
return sai55; 
//Modify new trial commnet vzx6778 mnbdsa732 cac311 dsad cxad2dsasd2 test claksd0909321 test dsa tes clasdas
// sldkjfsldkjflsdkjflskjdflkj
// sldkfjsldkfjdslknbcam321 nbbca6662 test compass 21
// sdlfkjds fldskjflksjdflsdkjflk/dsacv,nbdsdsavcbvnbdsa878211dsadsnab32111 tes clasd09321 test clkalsddaas
//sdfsdfdsf darte yelp test  bcte 7667211 test 8787782111 vcx432232ves433 dkdsa clas0932131 tes casd0321 tes cldsa0932131
// tets class90909321 gropu9832131
//test clkasd0909321 test0909
// tets cllasd090931 t76321
//test clkasd909321 t99882
//bcnbaoiuioudpsa
//mbcx989080291
//test871
//tes9891
//ts6761
//kjska
}         
}