public Class A3001
//HelloAR
{
public Account createAccount(String name) //method to create account
{
Account sai55= new Account();
sai55.Name = name;
return sai55; 
//Modify new trial commnet vzx6778 mnbdsa732 cac311 dsad cxad2dsasd2
// sldkjfsldkjflsdkjflskjdflkj
// sldkfjsldkfjdslknbcam321 nbbca6662 test compass 21
// sdlfkjds fldskjflksjdflsdkjflk/dsacv,nbdsdsavcbvnbdsa878211dsadsnab32111 tes clksad09321
//tes7676721]
//tes767621
//tes9009021
//tes0921
//testm,odify check
//test1
//test2
//test3
//test4
//test5
//atest7
//tes87
//jhjdshaoi
//jiljliass
//test1
//test2
//test3
//tes881
//hsaiosuyaoi
//sa7991
//hsao98790
//tes78781
//tes7871
//tes76762
//tes8782
//tesexternal
//external
//external1
//external2
}        
}