public Class A4001
//HelloAR
{
public Account createAccount(String name) //method to create account
{
Account sai55= new Account();
sai55.Name = name;
return sai55; 
//Modify new trial commnet vzx6778 mnbdsa732 cac311 dsad cxad2dsasd2
// sldkjfsldkjflsdkjflskjdflkj
// sldkfjsldkfjdslknbcam321 nbbca6662 test compass 21
// sdlfkjds fldskjflksjdflsdkjflk/dsacv,nbdsdsavcbvnbdsa878211dsadsnab32111 tes clksad09321
//mnsai7871
//nbsa9898291898219
//mnsaiu9
//te76731
//test8787817
//remote01
//remote02
//remote a4001 IDE
//demo change raleated to demo1 users
//test ckjas9891
//change001
//cga91
//ioy981
}        
}