public Class A444
//HelloAR
{
public Account createAccount(String name) //method to create account
{
Account sai55= new Account();
sai55.Name = name;
return sai55; 
//Modify new trial commnet vzx6778 mnbdsa732 cac311 dsad cxad2dsasd2
// sldkjfsldkjflsdkjflskjdflkj
// sldkfjsldkfjdslknbcam321 nbbca6662 test compass 21
// sdlfkjds fldskjflksjdflsdkjflk/dsacv,nbdsdsavcbvnbdsa878211dsadsnab32111 tes clksad09321
//mnsai7871
//nbsa9898291898219
//mnsaiu9
//te76731
//test8787817
//remote01
//remote02
//remote change 24 aug
//changes
//comment remote
//test clkas
//test chas8781
//ts7671
//test8787817
//tes6871
}        
}