public Class A9002
//Hel
{
public Account createAccount(String name) //method to create account
{
Account sai55= new Account();
sai55.Name = name;
return sai55; 
//Modify new trial commnet vzx6778 mnbdsa732 cac311 dsad cxad2dsasd2 test clasd 0909321321 test clkdsadsa test ca test cldsa3
// sldkjfsldkjflsdkjflsk
// sldkfjsldkfjdslknbcam321 nbbca6662 test compass 21 test clsa093131 test clasd90321
// sdlfkjds fldskjflksjdflsdkjflk/dsacv,nbdsdsavcbvnbdsa878211dsadsnab32111 test clasd90321
//test989281
//98989281
//test0909210921bfd dsnfdsf
//sajh989821kkk
//test01
//test02
//jsh98y291
//nsaoiuo21
}        
}