public Class saij1
{
public Account createAccount(String name)
{
//testsai
//testsai2
//testsai1
//testsai
//testsai2
//testsai1
Account j12= new Account();
j12.Name = name;
//Test78
//test89
return j12;
//Branch2Feb15
//test1
//test3
//Tes789
//test89
//test89
//test89
//test89
//test89
//test89
//test89
//test89
//test89
//Branch2Feb15
//test1
//test3
//Tes789
//test89
//test89
//test89
//test89
//test89
//test89
//test89
//test89
//test89
}
}