public Class A05
//HelloAR
{
public Account createAccount(String name) //method to create account
{
Account sai55= new Account();
sai55.Name = name;
return sai55; 
//Modify new trial commnet vzx6778 mnbdsa732 cac311 dsad cxad2dsasd2
// sldkjfsldkjflsdkjflskjdflkj
// sldkfjsldkfjdslknbcam321 nbbca6662 test compass 21
// sdlfkjds fldskjflksjdflsdkjflk/dsacv,nbdsdsavcbvnbdsa878211dsadsnab32111 tes clksad09321
//sdfsdfdsf darte yelp test  bcte 7667211 test 8787782111 vcx432232ves433 tes ca09321
// test claksd0909321 clossa force diduct
// test clkasd0932 deduct re98321321
// test source change 0001 source expect
//soyrce test check change 0921
// test external 87
}        
}