public Class A06
//HelloAR
{
public Account createAccount(String name) //method to create account
{
Account sai55= new Account();
sai55.Name = name;
return sai55; 
//Modify new trial commnet vzx6778 mnbdsa732 cac311 dsad cxad2dsasd2
// sldkjfsldkjflsdkjflskjdflkj
// sldkfjsldkfjdslknbcam321 nbbca6662 test compass 21
// sdlfkjds fldskjflksjdflsdkjflk/dsacv,nbdsdsavcbvnbdsa878211dsadsnab32111 tes c0909321 tes 09321
//sdfsdfdsf darte yelp test  bcte 7667211 test 8787782111 vcx432232ves433 tes clkasd0932131
// test class090909321 deduce 001 by 11212
//test clas09321 test001class0090921 check0021
//test source after build 001
//test claskd09e21
// tets ck9823vfgfgfg
//test class090921 cte check 0902910 test
//validate deploy 08989821
//dsa8887321fdfgf
//ljhdsaoiyudsa
//,bcxhziuq

}        
}